title: Captura
description: Capture Screen, Audio, Cursor, Mouse Clicks and Keystrokes
author: Mathew Sachin
url: "https://MathewSachin.github.io"
baseurl: "/Captura"
docs: "https://github.com/MathewSachin/Captura/blob/master/docs"

github: "https://github.com/MathewSachin/Captura"
paypal: "https://paypal.me/MathewSachin"
gitter: "https://gitter.im/MathewSachin/Captura"
appveyor: "https://ci.appveyor.com/project/MathewSachin/Captura"
gitter_room: "MathewSachin/Captura"

exclude: ["Gemfile", "Gemfile.lock", "README.md"]

plugins:
  - jekyll-seo-tag  # Search Engine Optimization
  - jekyll-sitemap # Site Map
  - jekyll-redirect-from
